spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: transactionServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: eventServiceCircuitBreaker
                fallbackUri: forward:/fallback

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 4
        failureRateThreshold: 100
        slowCallRateThreshold: 100
        waitDurationInOpenState: 60_000
        permittedNumberOfCallsInHalfOpenState: 2
        registerHealthIndicator: true
    instances:
      userServiceCircuitBreaker:
        baseConfig: default
      transactionServiceCircuitBreaker:
        baseConfig: default
      eventServiceCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
